### PR TITLE
Add "0" to _FALSE_STRINGS.

### PR DESCRIPTION
**Pull request by LEW21**

### CODE REVIEW

**Comment by doismellburning** [comment]
Thanks!

Alas I'm very reluctant to do this given that in terms of process exit code `0` is truth-y - a note I put in the documentation of equivalent functions I've written but apparently not here!

I don't have much data about usage here but I've definitely seen this be problematic in the past, but I'm interested in your perspective!

**Comment by LEW21** [comment]
In my team, we have a convention of using DEBUG=1 to enable debug mode for all our services. It has started because the most trivial way to get this variable from the environment was:
```python
DEBUG = bool(int(os.environ.get('DEBUG', '0')))
```

I guess it doesn't really matter, we could switch to on/off. However, I'm sure some people may think 0 is false, so we shouldn't silently assume it means true. We should treat it as false OR raise an exception (and if so - we should raise it for all numbers, because they can be exit codes too).

On one hand there is the case of exit codes, and on the other is the principle of the least surprise. I guess I'd choose treating 0 as false, as the exit code case seems really rare, and DEBUG=1 is probably much more common.

**Comment by doismellburning** [comment]
@LEW21 Thank you very much for the PR! Alas I've been somewhat unwell over the last 18 months and, while I'm (hopefully) better now, as you may have noticed, d12f has fallen off my radar slightly.

So, going forward, the wonderful @jdelic is taking over as maintainer.

Thank you again for the PR, sorry I've not gotten back to you sooner!

**Comment by LEW21** [comment]
Meanwhile, I've made my own [dj12](https://gitlab.com/aiakos/dj12).

**Comment by jdelic** [comment]
I agree with @LEW21 reasoning. Making 0 falsy in this case makes sense to me.

> Meanwhile, I've made my own dj12.
The beauty of open source at work :). Thanks for your submissions.

**Pull request merged**
