### PR TITLE
Multiple database support

### PR DESCRIPTION
**Pull request by doismellburning**
https://github.com/doismellburning/django12factor/issues/33
https://docs.djangoproject.com/en/1.7/topics/db/multi-db/

`TEST_DATABASE_URL` -> `settings.DATABASES['test']`

### CODE REVIEW

**Comment by doismellburning** [comment]
Needs:

* Some sort of warning/error behaviour if `DEFAULT_DATABASE_URL` is set
* Some sort of warning behaviour if `lowercase_DATABASE_URL` is set

**Comment by doismellburning** [comment]
@pendolf Right, how's that look to you?

**Comment by pendolf** [comment]
Checked in dev environment, worked perfectly. Thank you!

**Comment by doismellburning** [comment]
Wonderful, thanks for the idea and review!

**Comment by doismellburning** [comment]
(Will ship an actual release in the next day or so)

**Pull request merged**
