### PR TITLE
add pep484 stub file for type checking

### PR DESCRIPTION
**Pull request by jdelic**
because Python type checking is super cool

### CODE REVIEW

**Comment by doismellburning** [comment]
Do you know of a good way of automatically testing this for correctness? I don't want to end up accidentally breaking it later because I don't use the automagic type stuff...

**Comment by jdelic** [comment]
> because I don't use the automagic type stuff...

That's a mistake ;).

That said, we could just add a `mypy` run to TravisCI. I'll look into that.

**Comment by jdelic** [comment]
@doismellburning 
I refactored testing in this branch now to include mypy-lang which *installs only* on Python 2, so I couldn't solve the dependency conflict from `tox.ini` alone. TravisCI now offers easy testing against different Python versions without the previous hacks that were necessary ([see the up-to-date docs](https://docs.travis-ci.com/user/languages/python/)).

This branch now:
  * reuses tox virtual envs which speeds up the tests (which is good since we're now running 4 test environments on Travis)
  * runs Python 2.7, 3.4, 3.5 and 3.6 testing environments on TravisCI
  * The tox mypy testenv is only run on Python3 using a test against the TravisCI-supplied `$TRAVIS_PYTHON_VERSION` environment variable

This should completely cover the stub.

**Comment by jdelic** [comment]
(cough) ☝️ 👆

**Comment by jdelic** [comment]
(cough) (cough) ☝️ 👆

**Pull request merged**
